version: '3'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  
  web:
    build: .
    container_name: django_web
    command: python myproject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myproject
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
    networks:
      - backend
  
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
