# Generated by Django 3.2.25 on 2024-11-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigade_number', models.PositiveIntegerField(unique=True, verbose_name='Номер бригади')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'db_table': 'brigades',
            },
        ),
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50, unique=True, verbose_name='Реєстраційний номер')),
                ('depot', models.CharField(max_length=100, verbose_name='Депо')),
                ('locomotive_type', models.CharField(max_length=50, verbose_name='Тип локомотива')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Рік виготовлення')),
            ],
            options={
                'db_table': 'locomotives',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_code', models.CharField(max_length=50, unique=True, verbose_name='Код ремонту')),
                ('repair_type', models.CharField(max_length=100, verbose_name='Тип ремонту')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('days_required', models.PositiveIntegerField(verbose_name='Кількість днів')),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість за день')),
                ('brigade_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.brigade', verbose_name='Номер бригади')),
                ('reg_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.locomotive', verbose_name='Реєстраційний номер локомотива')),
            ],
            options={
                'db_table': 'repairs',
            },
        ),
    ]
